apiVersion: v1
kind: Secret
metadata:
  name: leernd-secret
  namespace: app-tst
type: Opaque
data:
  DB_USER: cG9zdGdyZXNfdXNlcg==
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  DB_NAME: cG9zdGdyZXM=
  DB_ENDPOINT: cG9zdGdyZXM=

  POSTGRES_USER: cG9zdGdyZXNfdXNlcg==
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  POSTGRES_DB: cG9zdGdyZXM=